version: '3.8'
services:
  mongodb:
    image: mongo:jammy
    ports:
      - 27031:27017
    env_file:
      - .env
    volumes:
      - dbdata6:/data/db
    networks:
      - mongo-network

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - mongo-network

volumes:
  dbdata6: 

networks: 
    mongo-network:
      driver: bridge