version: "3"
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - dbdata6:/data/db

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  pg-data:
  dbdata6: 
